# Numpy

*Numpy arryas are the main way we will use numpy*

*They come in two favors: **Vectors & Matrices** *

*Vectors are 1D and Matrix are 2D(can still have one row one col)*

In [1]:
list=[1,2,3]
list

[1, 2, 3]

In [2]:
import numpy as np

In [4]:
arr=np.array(list)
arr

array([1, 2, 3])

In [5]:
my_math=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_math)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Arange** is one of the most useful function for *quicly generating an array*

In [6]:
np.arange(0,10)
#indexing does upto 10, but does not include 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

 Creating **Identity Matrix**

2D square matrix, having ones in diagonal

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.random.rand(5)

array([0.31860116, 0.15041774, 0.47305949, 0.91984763, 0.31191998])

In [14]:
np.random.rand(3,3)

array([[0.30265439, 0.94887264, 0.42351647],
       [0.80734252, 0.38626543, 0.92528118],
       [0.39704804, 0.01872057, 0.19964596]])

In [15]:
np.random.randint(1,100)

42

In [16]:
np.random.randint(1,100,10)

array([23, 95, 15, 74, 54, 62,  5, 70, 80, 76])

In [17]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
random_arr=np.random.randint(0,50,10)
random_arr

array([38, 48, 32, 12, 44,  3,  3, 12, 16,  8])

In [19]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
random_arr.max()

48

In [21]:
random_arr.min()

3

In [22]:
random_arr.argmax()

1

In [23]:
#shape of a vector!
arr.shape

(25,)

In [24]:
#reshaping an array
arr=arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
arr.shape

(5, 5)

In [26]:
arr.dtype

dtype('int64')

Indexing and Selection!!

In [27]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr[4]

4

In [29]:
arr[1:5]

array([1, 2, 3, 4])

In [30]:
slice=arr[0:6]
slice


array([0, 1, 2, 3, 4, 5])

In [31]:
slice[:]

array([0, 1, 2, 3, 4, 5])

In [32]:
slice[:]=99
slice


array([99, 99, 99, 99, 99, 99])

In [33]:
arr


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [34]:
arr_copy=arr.copy()

In [35]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [36]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [37]:
arr_copy[:]=100

In [38]:
arr


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [39]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

**Indexing for 2D array**

In [40]:
arr_2d=np.array([[5,10,15],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [35, 40, 45]])

In [42]:
arr_2d[0][1]

10

In [43]:
arr_2d[0]

array([ 5, 10, 15])

In [44]:
arr_2d[:1,1:]

array([[10, 15]])

In [45]:
arr=np.arange(1,11)

In [46]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
bool_arr=arr>5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

We can use the above code, for **Conditional selection!**

In [49]:
arr[bool_arr]
#prints to true values

array([ 6,  7,  8,  9, 10])

In [51]:
arr_2d=np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

# Numpy Operations!

Arraye with Array

In [52]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [54]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [56]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [57]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [59]:
1/0

ZeroDivisionError: division by zero

In [60]:
#numpy wont give you the above error
arr/arr

<ipython-input-60-6690631ca601>:2: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [61]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [63]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [65]:
arr.max()

10

In [66]:
np.max(arr)

10